import { CategoriesEnum } from '../utility/enums.js';

export const gearKeywords = {
  accurate: `$${CategoriesEnum.Gear}#accurate$`,
  arcing: `$${CategoriesEnum.Gear}#arcing$`,
  armor_piercing: `$${CategoriesEnum.Gear}#armor_piercing$`,
  inaccurate: `$${CategoriesEnum.Gear}#inaccurate$`,
  knockback: `$${CategoriesEnum.Gear}#knockback$`,
  loading: `$${CategoriesEnum.Gear}#loading$`,
  ordnance: `$${CategoriesEnum.Gear}#ordnance$`,
  overkill: `$${CategoriesEnum.Gear}#overkill$`,
  overshield: `$${CategoriesEnum.Gear}#overshield$`,
  reliable_x: `$${CategoriesEnum.Gear}#reliable$`,
  seeking: `$${CategoriesEnum.Gear}#seeking$`,
  smart: `$${CategoriesEnum.Gear}#smart$`,
  threat_x: `$${CategoriesEnum.Gear}#threat_x$`,
  thrown_x: `$${CategoriesEnum.Gear}#thrown_x$`,
  deployable: `$${CategoriesEnum.Gear}#deployable$`,
  drone: `$${CategoriesEnum.Gear}#drone$`,
  grenade: `$${CategoriesEnum.Gear}#grenade$`,
  mine: `$${CategoriesEnum.Gear}#mine$`,
  mod: `$${CategoriesEnum.Gear}#mod$`,
  protocol: `$${CategoriesEnum.Gear}#protocol$`,
  shield: `$${CategoriesEnum.Gear}#shield$`,
  unique: `$${CategoriesEnum.Gear}#unique$`,
  ai: `$${CategoriesEnum.Gear}#ai$`,
  tags: `$${CategoriesEnum.Gear}#tags$`,
  limited_x: `$${CategoriesEnum.Gear}#limited_x$`,
};
